console.log("Owl-carousel");
$(document).ready(function(){
  $(".owl-carousel").owlCarousel({
      loop:true,
        margin:10,
        dots:false,
        responsiveClass:true,
        responsive:{
            0:{
                items:2,
                nav:true,
                loop:true
            },
            600:{
                items:3,
                nav:true,
                loop:true
            },
            1000:{
                items:5,
                nav:true,
                loop:true
            }
        }
  });
});